version: "3"

services:
  client:
    env_file:
      - .env
    build: ./client
    container_name: next-app
    image: next-app
    ports:
      - "5000:3000"

  server:
    env_file:
      - .env
    build: ./server
    container_name: express-app
    image: express-app
    ports:
      - "3000:3000"