services:
  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    image: krishuuu016/ai-server:v1
    container_name: express-app
    build: ./server
    env_file:
      - ./server/.env
    depends_on:
      - mongodb
    ports:
      - "3000:3000"

  client:
    image: krishuuu016/ai-client:v1
    container_name: next-app
    build: ./client
    env_file:
      - ./client/.env
    ports:
      - "5000:3000"

volumes:
  mongo-data: